# Generated by Django 6.0 on 2026-01-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0007_title_selection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='titleselection',
            new_name='pub_titlese_product_16b3bf_idx',
            old_name='pub_titlese_product_8020a2_idx',
        ),
        migrations.RenameIndex(
            model_name='titleselection',
            new_name='pub_titlese_planner_748b80_idx',
            old_name='pub_titlese_planner_dba44b_idx',
        ),
        migrations.RenameIndex(
            model_name='titleselection',
            new_name='pub_titlese_status_3b4c8a_idx',
            old_name='pub_titlese_status_b7b7b7_idx',
        ),
        migrations.AlterField(
            model_name='templatepart',
            name='part_type',
            field=models.CharField(choices=[('keyword', 'Keyword'), ('axis_attribute', 'Axis Attribute'), ('attribute_value', 'Attribute Value'), ('head_term', 'Head Term'), ('hook_term', 'Hook Term'), ('literal', 'Literal'), ('brand', 'Brand')], max_length=20),
        ),
    ]
