# Generated by Django 6.0 on 2026-01-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0009_title_generation_policy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='titleselection',
            name='pub_titlese_product_16b3bf_idx',
        ),
    ]
