# Generated by Django 6.0 on 2026-01-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0010_remove_titleselection_pub_titlese_product_16b3bf_idx'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE pub_channellocalepolicy DROP CONSTRAINT IF EXISTS uniq_channel_locale_policy;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE pub_titleselection DROP CONSTRAINT IF EXISTS uniq_title_selection_scope;",
            reverse_sql="",
        ),
    ]
