# Generated by Django 6.0.1 on 2026-01-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0017_unique_title_registry'),
    ]

    operations = [
        # No-op migration: constraints may or may not exist
        # This migration exists only to satisfy dependency for catalog.0016
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
