# Generated by Django 6.0.1 on 2026-01-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0021_make_channel_listing_product_optional'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='channellocalepolicy',
            name='uniq_channel_locale_policy',
        ),
        migrations.RemoveConstraint(
            model_name='titleselection',
            name='uniq_title_selection_scope',
        ),
    ]
