# Generated by Django 6.0.1 on 2026-01-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_importcolumnrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimport',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('mapped', 'Mapped'), ('processing', 'Processing'), ('completed', 'Completed'), ('committed', 'Committed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
