# Generated by Django 6.0.1 on 2026-01-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0015_import_parent_variant_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimport',
            name='group_by_product_key',
            field=models.BooleanField(default=True, help_text="If True, variants with the same PRODUCT_KEY will be grouped into one Product. If False, each variant will get its own Product (standalone mode) for manual grouping later. PRODUCT_KEY column will still be parsed but won't be used for grouping."),
        ),
    ]
