# Generated by Django 6.0.1 on 2026-01-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0018_add_parse_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importcolumnrule',
            name='role',
            field=models.CharField(choices=[('PRODUCT_KEY', 'Product key (parent)'), ('VARIANT_KEY', 'Variant key (SKU)'), ('CATEGORY', 'Category'), ('BRAND', 'Brand'), ('TITLE', 'Title'), ('DESCRIPTION', 'Description'), ('BARCODE', 'Barcode'), ('MPN', 'MPN (Manufacturer Part Number)'), ('SOURCE_SKU', 'Source SKU'), ('SOURCE_SUPPLIER', 'Source Supplier'), ('SOURCE_LOCALE', 'Source Locale'), ('PRODUCT_MODEL', 'Product Model'), ('PRODUCT_SERIES', 'Product Series'), ('PRODUCT_CODE', 'Product Code'), ('ATTRIBUTE', 'Attribute'), ('IGNORE', 'Ignore')], default='ATTRIBUTE', max_length=32),
        ),
    ]
