# Generated by Django 6.0 on 2026-01-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_variant_barcode_mpn'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variant',
            name='uniq_variant_barcode',
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('barcode',), name='uniq_variant_barcode'),
        ),
    ]
