# Generated by Django 6.0 on 2026-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='category_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
