# Generated by Django 6.0 on 2026-01-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_producttype_category_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='main_category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
