# Generated by Django 6.0.1 on 2026-01-21 16:10

from django.db import migrations, models, connection


def check_column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = %s AND column_name = %s
            )
        """, [table_name, column_name])
        return cursor.fetchone()[0]


def copy_source_fields_to_variants(apps, schema_editor):
    """Copy source_* fields from Product to its variants"""
    Product = apps.get_model('catalog', 'Product')
    Variant = apps.get_model('catalog', 'Variant')
    
    # Only copy if Product still has source fields
    if check_column_exists('catalog_product', 'source_title'):
        for product in Product.objects.all():
            # Copy source fields from product to all its variants
            if any([
                product.source_title,
                product.source_description,
                product.source_sku,
                product.source_supplier,
                product.source_locale
            ]):
                Variant.objects.filter(product=product).update(
                    source_title=product.source_title or '',
                    source_description=product.source_description or '',
                    source_sku=product.source_sku or '',
                    source_supplier=product.source_supplier or '',
                    source_locale=product.source_locale or '',
                )


def reverse_copy_source_fields(apps, schema_editor):
    """Reverse: copy source_* from first variant back to product (if needed)"""
    Product = apps.get_model('catalog', 'Product')
    Variant = apps.get_model('catalog', 'Variant')
    
    for product in Product.objects.all():
        first_variant = Variant.objects.filter(product=product).first()
        if first_variant:
            product.source_title = first_variant.source_title or ''
            product.source_description = first_variant.source_description or ''
            product.source_sku = first_variant.source_sku or ''
            product.source_supplier = first_variant.source_supplier or ''
            product.source_locale = first_variant.source_locale or ''
            product.save(update_fields=['source_title', 'source_description', 'source_sku', 'source_supplier', 'source_locale'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productattributevalue_is_axis'),
    ]

    operations = [
        # Step 1: Add fields to Variant first (only if they don't exist)
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'catalog_variant' AND column_name = 'source_description') THEN
                        ALTER TABLE catalog_variant ADD COLUMN source_description TEXT DEFAULT '' NOT NULL;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'catalog_variant' AND column_name = 'source_locale') THEN
                        ALTER TABLE catalog_variant ADD COLUMN source_locale VARCHAR(15) DEFAULT '' NOT NULL;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'catalog_variant' AND column_name = 'source_sku') THEN
                        ALTER TABLE catalog_variant ADD COLUMN source_sku VARCHAR(150) DEFAULT '' NOT NULL;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'catalog_variant' AND column_name = 'source_supplier') THEN
                        ALTER TABLE catalog_variant ADD COLUMN source_supplier VARCHAR(100) DEFAULT '' NOT NULL;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'catalog_variant' AND column_name = 'source_title') THEN
                        ALTER TABLE catalog_variant ADD COLUMN source_title TEXT DEFAULT '' NOT NULL;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Copy data from Product to Variant (if Product still has fields)
        migrations.RunPython(copy_source_fields_to_variants, reverse_copy_source_fields),
        # Step 3: Remove fields from Product (only if they exist)
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'catalog_product' AND column_name = 'source_description') THEN
                        ALTER TABLE catalog_product DROP COLUMN source_description;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'catalog_product' AND column_name = 'source_locale') THEN
                        ALTER TABLE catalog_product DROP COLUMN source_locale;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'catalog_product' AND column_name = 'source_sku') THEN
                        ALTER TABLE catalog_product DROP COLUMN source_sku;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'catalog_product' AND column_name = 'source_supplier') THEN
                        ALTER TABLE catalog_product DROP COLUMN source_supplier;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'catalog_product' AND column_name = 'source_title') THEN
                        ALTER TABLE catalog_product DROP COLUMN source_title;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
