# Generated by Django 6.0.1 on 2026-01-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_move_source_fields_to_variant'),
        ('pub', '0018_add_channel_variant_axis'),
    ]

    operations = [
        # Note: source fields were already moved from Product to Variant in migration 0015
        # We only need to create the ChannelVariantAxis model here
        migrations.CreateModel(
            name='ChannelVariantAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('label_override', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_variant_axes', to='catalog.attribute')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_axes', to='pub.channel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_variant_axes', to='catalog.product')),
            ],
            options={
                'ordering': ['product', 'channel', 'position'],
                'indexes': [models.Index(fields=['product', 'channel', 'position'], name='idx_channel_axis_position'), models.Index(fields=['channel'], name='idx_channel_axis_channel')],
                'constraints': [models.UniqueConstraint(fields=('product', 'channel', 'attribute'), name='uniq_channel_variant_axis')],
            },
        ),
    ]
