# Generated by Django 6.0.1 on 2026-01-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_add_channel_listing_axis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='source_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='source_locale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='source_sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='source_supplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='source_title',
        ),
        migrations.AddField(
            model_name='variant',
            name='source_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='variant',
            name='source_locale',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='variant',
            name='source_sku',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='variant',
            name='source_supplier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='source_title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
