# Generated by Django 6.0 on 2026-01-05 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_source_fields'),
        ('content', '0010_producttypesynonym'),
        ('kw', '0008_keyword_parse'),
        ('pub', '0005_template_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerrun',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='plannerrun',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_runs', to='catalog.producttype'),
        ),
        migrations.AddField(
            model_name='plannerrunkeyword',
            name='classifier',
            field=models.CharField(blank=True, choices=[('rule', 'Rule'), ('llm', 'LLM'), ('manual', 'Manual')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='plannerrunkeyword',
            name='concept',
            field=models.CharField(blank=True, choices=[('head', 'Head'), ('attribute', 'Attribute'), ('attribute_value', 'Attribute Value'), ('intent', 'Intent'), ('negative', 'Negative')], db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='plannerrunkeyword',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='plannerrunkeyword',
            name='mapped_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_run_keywords', to='catalog.attribute'),
        ),
        migrations.AddField(
            model_name='plannerrunkeyword',
            name='mapped_attribute_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_run_keywords', to='catalog.attributevalue'),
        ),
        migrations.AddField(
            model_name='plannerrunkeyword',
            name='mapped_product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_run_keywords', to='catalog.producttype'),
        ),
        migrations.AddField(
            model_name='plannerrunkeyword',
            name='reason_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plannerrunkeyword',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='suggested', max_length=16),
        ),
        migrations.AddField(
            model_name='plannerseed',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_seeds', to='pub.channel'),
        ),
        migrations.AddField(
            model_name='plannerseed',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_seeds', to='catalog.producttype'),
        ),
        migrations.AlterField(
            model_name='plannerseed',
            name='seed_type',
            field=models.CharField(choices=[('head', 'Head'), ('feature', 'Feature'), ('brand', 'Brand')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='plannerrunkeyword',
            index=models.Index(fields=['run', 'concept', 'status'], name='idx_prk_run_concept_status'),
        ),
        migrations.AddIndex(
            model_name='plannerrunkeyword',
            index=models.Index(fields=['mapped_product_type', 'status'], name='idx_prk_mpt_status'),
        ),
        migrations.AddIndex(
            model_name='plannerrunkeyword',
            index=models.Index(fields=['mapped_attribute_value', 'status'], name='idx_prk_mav_status'),
        ),
        migrations.AddIndex(
            model_name='plannerseed',
            index=models.Index(fields=['locale', 'product_type', 'channel', 'is_active'], name='idx_planner_seed_scope'),
        ),
    ]
