# Generated by Django 6.0 on 2026-01-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_producttype_main_category'),
        ('kw', '0009_plannerrun_country_code_plannerrun_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributemap',
            name='origin_run_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_maps', to='kw.plannerrunkeyword'),
        ),
        migrations.AddField(
            model_name='keywordconcept',
            name='origin_run_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_suggestions', to='kw.plannerrunkeyword'),
        ),
        migrations.AddField(
            model_name='producttypemap',
            name='origin_run_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type_maps', to='kw.plannerrunkeyword'),
        ),
        migrations.AddField(
            model_name='producttypemap',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='suggested', max_length=20),
        ),
        migrations.AddField(
            model_name='producttypemap',
            name='tagged_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producttypemap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plannerseed',
            name='seed_type',
            field=models.CharField(choices=[('head', 'Head'), ('feature', 'Feature'), ('brand', 'Brand'), ('competitor', 'Competitor'), ('category', 'Category')], max_length=20),
        ),
    ]
