# Generated by Django 6.0 on 2026-01-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw', '0014_product_keyword_map_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkeywordmap',
            name='source',
            field=models.CharField(choices=[('enum_map', 'Enum Map'), ('pav_text', 'PAV Text'), ('pav_text_i18n', 'PAV Text (i18n)'), ('pav_text_llm', 'PAV Text (LLM)'), ('pav_numeric', 'PAV Numeric'), ('attr_value_label', 'Attribute Value Label'), ('attr_value_code', 'Attribute Value Code')], max_length=20),
        ),
    ]
