# Generated by Django 6.0 on 2026-01-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producti18n',
            name='uniq_locale_slug_when_set',
        ),
        migrations.AddConstraint(
            model_name='producti18n',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False), models.Q(('slug', ''), _negated=True)), fields=('locale', 'slug'), name='uniq_locale_slug_when_set'),
        ),
    ]
