# Generated by Django 6.0 on 2026-01-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_attribute_value_synonyms'),
        ('content', '0003_producttype_i18n'),
    ]

    operations = [
    ]
