# Generated by Django 6.0 on 2026-01-05 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_source_fields'),
        ('content', '0009_translationtask'),
        ('kw', '0008_keyword_parse'),
        ('pub', '0005_template_versioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='suggested', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('source', models.CharField(default='gads_keyword_planner', max_length=64)),
                ('reason_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_type_synonyms', to='pub.channel')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type_synonyms', to='kw.keyword')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_type_synonyms', to='content.locale')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='catalog.producttype')),
            ],
            options={
                'indexes': [models.Index(fields=['product_type', 'locale', 'channel', 'status', 'is_active'], name='idx_ptsyn_lookup')],
                'constraints': [models.UniqueConstraint(fields=('product_type', 'locale', 'channel', 'term'), name='uq_ptsyn_pt_loc_ch_term')],
            },
        ),
    ]
