# Generated by Django 6.0 on 2026-01-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_producttypesynonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypei18n',
            name='main_category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
