# Generated by Django 6.0.1 on 2026-01-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_add_translation_task_model'),
        ('pub', '0022_remove_channellocalepolicy_uniq_channel_locale_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationtask',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Optional channel filter for translation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_tasks', to='pub.channel'),
        ),
    ]
